//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public string Link { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Target { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> TypeID { get; set; }
    }
}
